### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by patelvanita360** [ForNeVeR/kaiwa#233]
Hello @vitalyster ,

When I am compiling kaiwa on server its giving me following error while in local system its working properly.

Can you please help me solve this issue ?
```
[10:43:29] Finished 'jade-templates' after 914 ms
[10:43:29] Starting 'client'...
[10:43:29] 'client' errored after 1.69 ms
[10:43:29] TypeError: Object function Object() { [native code] } has no method 'assign'
    at Gulp.<anonymous> (/var/www/html/kaiwa/Gulpfile.js:43:20)
    at module.exports (/var/www/html/kaiwa/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/html/kaiwa/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/html/kaiwa/node_modules/orchestrator/index.js:214:10)
    at /var/www/html/kaiwa/node_modules/orchestrator/index.js:279:18
    at finish (/var/www/html/kaiwa/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/var/www/html/kaiwa/node_modules/orchestrator/lib/runTask.js:29:3)
    at /var/www/html/kaiwa/node_modules/templatizer/templatizer.js:258:25
    at /var/www/html/kaiwa/node_modules/vinyl-file/node_modules/graceful-fs/graceful-fs.js:43:10
    at /var/www/html/kaiwa/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
[10:43:29] Finished 'resources' after 925 ms

npm ERR! kaiwa.im@1.1.0 compile: `gulp compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kaiwa.im@1.1.0 compile script.
npm ERR! This is most likely a problem with the kaiwa.im package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls kaiwa.im
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "compile"
npm ERR! cwd /var/www/html/kaiwa
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/kaiwa/npm-debug.log
npm ERR! not ok code 0

```

**Comment by ForNeVeR** [comment]
Your node is outdated. Please use a supported version (as of now, we support 8.11 onward).
